name: baguncart_flutter
description: Sistema administrativo BaguncArt em Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mysql1: 0.20.0
  crypto: 3.0.3
  shared_preferences: 2.2.2
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true
